using Bonobo.Git.Server.Configuration;
using Bonobo.Git.Server.Data;
using Bonobo.Git.Server.Models;
using Serilog;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Text;
using Unity;

namespace Bonobo.Git.Server.Security
{
    public interface IAuthorizedKeysSynchronizer
    {
        /// <summary>
        /// Rewrites the whole authorized_keys file from the current set of keys. Called whenever a
        /// key is added or removed, and once at start-up so that a lost or stale file repairs itself.
        /// </summary>
        void Synchronize();
    }

    /// <summary>
    /// Generates the authorized_keys file that Windows OpenSSH reads for the git account.
    ///
    /// Every key is written with a forced command, so that authenticating with a Bonobo key can only
    /// ever start Bonobo.Git.Server.SshShell.exe - never a shell. The key's own id is passed as the
    /// single argument, which is how the shell knows who is connecting: sshd has already proved
    /// possession of the private key by the time the command runs.
    ///
    /// The file is written whole, never appended to, so removing a key in the UI removes the access.
    /// </summary>
    public class AuthorizedKeysSynchronizer : IAuthorizedKeysSynchronizer
    {
        /// <summary>
        /// Deliberately spelled out rather than using the newer 'restrict' keyword, which only exists
        /// in OpenSSH 7.2 and later.
        /// </summary>
        private const string KeyOptions = "no-port-forwarding,no-agent-forwarding,no-X11-forwarding,no-pty";

        private static readonly object FileLock = new object();

        [Dependency]
        public ISshKeyRepository SshKeyRepository { get; set; }

        public void Synchronize()
        {
            if (!SshSettings.IsConfigured)
            {
                Log.Verbose("SSH: Not configured, skipping authorized_keys synchronization");
                return;
            }

            try
            {
                var keys = SshKeyRepository.GetAllKeys();
                WriteFile(SshSettings.AuthorizedKeysPath, BuildFileContent(SshSettings.ShellPath, keys));
                Log.Information("SSH: Wrote {KeyCount} key(s) to {Path}", keys.Count, SshSettings.AuthorizedKeysPath);
            }
            catch (Exception ex)
            {
                // A failure here means the file on disk no longer matches the database. That is worth
                // shouting about, but it must not take down the request that triggered it - the
                // start-up synchronization will try again.
                Log.Error(ex, "SSH: Failed to write authorized_keys to {Path}", SshSettings.AuthorizedKeysPath);
            }
        }

        /// <summary>
        /// Builds the file content. Kept separate from the file handling so it can be tested directly.
        /// </summary>
        public static string BuildFileContent(string shellPath, IEnumerable<SshKeyModel> keys)
        {
            var builder = new StringBuilder();
            builder.Append("# Generated by Bonobo Git Server. Do not edit - this file is rewritten\n");
            builder.Append("# whenever a user adds or removes an SSH key, and any manual changes are lost.\n");

            foreach (var key in keys.OrderBy(k => k.CreatedAt))
            {
                // The forced command is handed to the git account's shell, so the path is quoted for
                // the shell first, and then the whole thing is escaped for authorized_keys.
                var command = "\"" + shellPath + "\" " + key.Id.ToString("D");

                builder.Append("command=\"");
                builder.Append(EscapeOptionValue(command));
                builder.Append("\",");
                builder.Append(KeyOptions);
                builder.Append(' ');
                builder.Append(key.PublicKey);
                builder.Append('\n');
            }

            return builder.ToString();
        }

        /// <summary>
        /// Inside a quoted authorized_keys option sshd unescapes \\ and \", which matters here
        /// because every Windows path is full of backslashes.
        /// </summary>
        private static string EscapeOptionValue(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static void WriteFile(string path, string content)
        {
            lock (FileLock)
            {
                var directory = Path.GetDirectoryName(path);
                if (!String.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                // Write beside the real file and move into place, so that a connection arriving
                // mid-write never sees a half-written key list.
                var temporaryPath = path + ".tmp";
                File.WriteAllText(temporaryPath, content, new UTF8Encoding(false));

                if (SshSettings.HardenAuthorizedKeysPermissions)
                {
                    HardenPermissions(temporaryPath);
                }

                if (File.Exists(path))
                {
                    File.Delete(path);
                }
                File.Move(temporaryPath, path);
            }
        }

        /// <summary>
        /// Windows OpenSSH refuses to use an authorized_keys file that other accounts can write to,
        /// so we remove inherited access and grant only SYSTEM, Administrators and the account sshd
        /// reads the file as. Best-effort: if the app pool identity does not own the file it cannot
        /// change the ACL, and an administrator has to do it once by hand.
        /// </summary>
        private static void HardenPermissions(string path)
        {
            try
            {
                var file = new FileInfo(path);
                var security = file.GetAccessControl();

                security.SetAccessRuleProtection(true, false);

                foreach (FileSystemAccessRule existing in security.GetAccessRules(true, false, typeof(SecurityIdentifier)))
                {
                    security.RemoveAccessRule(existing);
                }

                Grant(security, new SecurityIdentifier(WellKnownSidType.LocalSystemSid, null), FileSystemRights.FullControl);
                Grant(security, new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid, null), FileSystemRights.FullControl);

                // The app pool identity has to keep writing the file on every key change
                using (var currentUser = WindowsIdentity.GetCurrent())
                {
                    if (currentUser != null && currentUser.User != null)
                    {
                        Grant(security, currentUser.User, FileSystemRights.FullControl);
                    }
                }

                if (!String.IsNullOrWhiteSpace(SshSettings.ServiceAccount))
                {
                    Grant(security, new NTAccount(SshSettings.ServiceAccount), FileSystemRights.Read);
                }

                file.SetAccessControl(security);
            }
            catch (Exception ex)
            {
                Log.Warning(ex,
                    "SSH: Could not tighten permissions on {Path}. sshd will refuse the file unless an administrator " +
                    "restricts it to SYSTEM, Administrators and the git account.", path);
            }
        }

        private static void Grant(FileSecurity security, IdentityReference identity, FileSystemRights rights)
        {
            security.AddAccessRule(new FileSystemAccessRule(identity, rights, AccessControlType.Allow));
        }
    }
}
